### PR TITLE
Fixes which biomes rabbits spawn in when enabled

### PR DESCRIPTION
**Pull request by pupnewfster**
When injecting rabbit spawn is uncommented this will have them spawn in the correct biomes

### CODE REVIEW

**Comment by unicxa** [comment]
Was going to also update to have a enabler in the Config.yml if you can you can add this I'm kinda busy :-)

**Comment by pupnewfster** [comment]
Might as well will also make it so that it is easier to add the other new mobs without having to change default file again

**Comment by unicxa** [comment]
True. thanks again i would get to it but today alot is going on

**Comment by pupnewfster** [comment]
mobSpawning.endermites config option will cause endermites to spawn I will push in a different file after doing this because they spawn from enderpearls not just in a specific biome

**Comment by pupnewfster** [comment]
Endermites do not actually spawn, just the logic behind them spawning is in. The things I tried for actually spawning them  did not work so I just left a comment for location to spawn them.

**Comment by NavidK0** [comment]
This pull request needs to be updated so we can automatically merge it.

**Comment by pupnewfster** [comment]
working on updating it not entirely sure  if easy method or if I should just resubmit pull request after manually merging

**Comment by pupnewfster** [comment]
Infact that is what I will do as I already had updated so it could be merged just it still thinks things changed so will just recreate a pull request

**Pull request closed without merging**
