### PR TITLE
[PR] Added title command!

### PR DESCRIPTION
**Pull request by matthijs2704**
Added the title command. You can either use normal text with color codes (&4 is red) or you can use the new Raw JSON titles. The command works like the vanilla/SSP command and uses the same arguments and such.

### CODE REVIEW

**Comment by Shevchik** [comment]
Fix that vildcard imports. They only bring trouble.

**Comment by Jikoo** [comment]
Wouldn't it be best to check the client version of the target before executing the command? Would be easier than intercepting packets later.

**Comment by matthijs2704** [comment]
Whoops, I forgot to copy that part from my testing plugin, thanks for noticing!

**Comment by Shevchik** [comment]
Checking vesion is not needed. We intercept and drop invalid packets for 1.7 client  anyway.

**Comment by Jikoo** [comment]
Hm, all right, figured it'd make more sense to warn and not even try to send it than try to send it and block it later.

**Comment by matthijs2704** [comment]
I'm not sending it right now when the protocol version isn't 47 or higher right? I'm sending to the sender that the title command can't be send to the receiver. So what should I change now?

**Comment by Shevchik** [comment]
Remove unneeded changes on other files, like import order and such.

**Comment by matthijs2704** [comment]
All right done. As said in the description, I changed the settings of IntelliJ so this won't happen again.

**Pull request merged**
