### PR TITLE
Create CarbonEntityGenartor.java

### PR DESCRIPTION
**Pull request by unicxa**
*New Genartor
Adds a class to allow Rabbits to spawn in biome's by default 
Goto line 67 to edit Probablility, minSpawn, maxSpawn

### CODE REVIEW

**Comment by NavidK0** [comment]
Why is the method empty for EventHandler?

Also, since this is a Bukkit chunk generator, does this have to be added to the bukkit.yml file for the server?

**Comment by unicxa** [comment]
Nope I tested it just a minute ago no need to add anything to a YML, But two things i would do is change the probability and the max and min spawning lower. Also try adding to enabler to the plugin's config.yml

**Comment by unicxa** [comment]
also remove eventhander() @line 38

**Comment by NavidK0** [comment]
Thanks.

**Pull request merged**
